/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ePortfolioMaker;

/**
 *
 * @author Jeanmarie Vargas
 */
public enum LanguagePropertyType {
   // TITLE FOR WINDOW TITLE BAR
   TITLE_WINDOW,
   
   //APPLICATION TOOLTIPS FOR BUTTONS
   TOOLTIP_NEW_PORTFOLIO,
   TOOLTIP_LOAD_PORTFOLIO,
   TOOLTIP_SAVE_PORTFOLIO,
   TOOLTIP_SAVE_AS,
   TOOLTIP_EXPORT,
   TOOLTIP_EXIT,
   
   TOOLTIP_PAGE_EDITOR,
   TOOLTIP_SITE_VIEWER,
        
   TOOLTIP_ADD_NEW_PAGE,
   TOOLTIP_REMOVE_PAGE,
   TOOLTIP_SELECT_LAYOUT_TEMPLATE,
   TOOLTIP_SELECT_COLOR_TEMPLATE,
   TOOLTIP_SELECT_BANNER_IMAGE,
        
   TOOLTIP_SELECT_COMP_FONT,
        
   TOOLTIP_UPDATE_PAGE_TITLE,
   TOOLTIP_UPDATE_STUDENT_NAME,
   TOOLTIP_UPDATE_FOOTER,
        
   TOOLTIP_ADD_TEXT_COMP,
   TOOLTIP_ADD_IMAGE_COMP,
   TOOLTIP_ADD_SLIDESHOW_COMP,
   TOOLTIP_ADD_VIDEO_COMP,
   TOOLTIP_ADD_HYPERLINK,
   TOOLTIP_REMOVE_COMP,
   
   TOOLTIP_ADD_PARAGRAPH,
   TOOLTIP_ADD_HEADER,
   TOOLTIP_ADD_LIST,
   TOOLTIP_ADD_LIST_ELEMENT,
        
   TOOLTIP_NAVIGATE_SITE,
   
   TOOLTIP_ADD_SLIDE,
   TOOLTIP_REMOVE_SLIDE,
   TOOLTIP_MOVE_UP,
   TOOLTIP_MOVE_DOWN,
   TOOLTIP_PREVIOUS_SLIDE,
   TOOLTIP_NEXT_SLIDE,
   DEFAULT_IMAGE_CAPTION,
   DEFAULT_PAGE_TITLE,
   LABEL_CAPTION,
   LABEL_SLIDESHOW_TITLE,
   
   
   //UI LABELS
   
   
   ERROR_HANDLING,
   ERROR_DATA_FILE_LOADING,
   ERROR_PROPERTIES_FILE_LOADING,
   ERROR_NO_SLIDESHOW_IMAGES,
   ERROR_UNEXPECTED
   
   
}
